---
- name: Ansible report job
  hosts: all
  gather_facts: True
  tasks:


    - name: Windows Install pkg role
      include_role:
        name: windows_install

    - name: Configure centrify 
      include_role:
        name: windows_centrify
