- name: collect facts about system services
  service_facts:

- name: Debug
  debug:
    var: ansible_facts.services["autofs.service"]


- name: Print only this task
  debug:
   msg: "print this task"
#  when: ansible_facts.services["autofs.service"].state == 'stopped'  
#  when: ansible_facts.services['{{ servey_status }}'].state == 'stopped'  
  when: ansible_facts.services[servey_status].state == 'stopped'  
