---

- name: check to see if server has package updates
  ansible.builtin.shell: dnf list --updates | awk 'f;/Available Upgrades/{f=1}' | awk '{ print $1}'
  register: updates

- name: display count
  debug:
    msg: "Found {{ updates.stdout_lines | length }} packages to be updated"

- block:
   - name: Update server if packages are available
     ansible.builtin.dnf:
       name: "*"
       state: latest
     when: updates.stdout_lines | length > 0

   - name: Check of the server requires a reboot after patching
     shell: needs-restarting -r 
     register: reboot_required
     
   - name: print reboot status
     debug:
       msg: Server requires a reboot
     when: reboot_required.rc !=0 
