---

- name: check to see if server has package updates
  shell: dnf list --updates | awk 'f;/Available Upgrades/{f=1}' | awk '{ print $1}'
  changed_when: updates.stdout_lines | length > 0
  args:
    warn: false
  register: updates

- name: display count
  debug:
    msg: "Found {{ updates.stdout_lines | length }} packages to updated"
