---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

dependencies:
  galaxy:
    collections:
    - community.vmware
  python:
    - pytest

options:
  package_manager_path: /usr/bin/microdnf
