---

pre_tasks:
  
  - name: create output folder
    run_onces: yes
    ansible.builtin.file:
      path: /var/tmp/reports
      state: directory
tasks:

  - name: Debug
    debug:
      msg: "test"
