---

    - name: Ping Red Hat Enterprise Linux Servers
      ansible.builtin.ping:
      register: ping_result

    - name: Calculate Reachability Percentage
      ansible.builtin.set_fact:
        cacheable: true
        reachable: "{{ ansible_play_hosts | length }}"
        total_servers: "{{ ansible_play_hosts_all | length }}"

    - name: list failed hosts
      ansible.builtin.debug:
        msg: "{{ ansible_play_hosts_all | difference(ansible_play_hosts) }}"
      run_once: true 

    - name: Populate results into connectivity report
      ansible.builtin.template:
        src: connectivity_l.j2
        dest: /var/www/html/index.html
        mode: "0644"
        owner: apache
        group: apache
      delegate_to: ansible-ee.rydzinski.local
