---
- name: Install the couple of packages
  ansible.builtin.dnf:
    name:
      - vim
      - wget
    state: latest
#  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'

- name: Install couple of packages using a vars file
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: latest
  with_items: "{{ packages }"

