- name: Counter
  set_fact:
    next_host: "{{ number | int + 1 }}"

- name: set a fact based on a variable
  set_fact:
    server_name: "{{ datacenter }}{{ application }}{{ tier }}{{ next_host }}"

- name: Print
  debug:
    msg: "{{ server_name }}"

#- set_fact:
#    new_vm_name: "{{ firstpart }}-{{ (((server_list | sort | max).split('-'))[1]| int) + 1 }}"
#  delegate_to: localhost

#- name: print name
#   debug:
#     var: {{ new_vm_name }}
