- name: set a fact based on a variable
  set_fact:
    server_name: "{{ datacenter }}{{ application }}{{ tier }}{{ next_host | int + 1 }}"

- name: Print
  debug:
    msg: "{{ server_name }}"

- name: Api call
  ansible.builtin.uri:
    url: hhttp://192.168.1.142:3000/servers
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: result
  
- name: print output
  debug:
    msg: "{{ result }}"

#- set_fact:
#    new_vm_name: "{{ firstpart }}-{{ (((server_list | sort | max).split('-'))[1]| int) + 1 }}"
#  delegate_to: localhost

#- name: print name
#   debug:
#     var: {{ new_vm_name }}
#- name: Counter
#  set_fact:
#    next_host: "{{ number | int + 1 }}"
