- name: set a fact based on a variable
  set_fact:
    server_name: "{{ datacenter }}{{ application }}{{ tier }}{{ next_host | int + 1 }}"

- name: Print
  debug:
    msg: "{{ server_name }}"

- name: Api call
  ansible.builtin.uri:
    url: http://192.168.1.142:3000/servers
    method: GET
    return_content: yes
    headers:
      Accept: application/json
  register: hosts_data
  delegate_to: localhost
  
#- name: print output
#  debug:
#    msg: "{{ host_data }}"

- set_fact:
    hosts_all: "{{ groups['servers'] | map('regex_replace', 'app(\\d+)', '\\1') | map('int') | sort | map('regex_replace', '^', 'app') | list }}" 

- name: print
  debug:
    var: hosts_all

#- set_fact:
#    new_vm_name: "{{ firstpart }}-{{ (((server_list | sort | max).split('-'))[1]| int) + 1 }}"
#  delegate_to: localhost

#- name: print name
#   debug:
#     var: {{ new_vm_name }}
#- name: Counter
#  set_fact:
#    next_host: "{{ number | int + 1 }}"
